version: '3'
services:
  flask:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    image: "python-barcode:latest"
    deploy:
      replicas: 4
    command: python3 app.py
